### ISSUE TITLE
CAN YOU MENTION THE HEADER CORE FUNCTIONALLITY

### ISSUE THREAD

**Issue by itsdlhqcp** [itsnitinr/dogecoin-ticker#1]
YOUR APP FOR FETCHING DATA FROM WAZIRUX API NO LONGER WORKING AS THE FILE YOU HOST FROM HEROKU NO LONGER ON NETWORK---CAN YOU PLEASE mention that  HEADER CORE PACKAGE-I NEED TO LINK WITH YOUR PROJECT TO MAKE ANOTHER APPLICATION OF CRYPTO ALERT .....SO AS..

**Comment by itsnitinr** [comment]
Take a look at this: https://www.npmjs.com/package/cors-anywhere

Hope this helps. Feel free to reopen this issue if you need further help.
